name: Send Fun Fact Email

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  send-fun-fact-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send fun fact email
        run: |
          curl --request GET https://vivacious-leta-kage1234-a7768371.koyeb.app/send-fun-fact
        env:
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.PASSWORD }}
